INSERT INTO users (email, password_hash)
VALUES
('user1@example.com', 'hashed_pw_user1'),
('user2@example.com', 'hashed_pw_user2'),
('user3@example.com', 'hashed_pw_user3'),
('user4@example.com', 'hashed_pw_user4'),
('user5@example.com', 'hashed_pw_user5'),
('user6@example.com', 'hashed_pw_user6'),
('user7@example.com', 'hashed_pw_user7'),
('user8@example.com', 'hashed_pw_user8'),
('user9@example.com', 'hashed_pw_user9'),
('user10@example.com', 'hashed_pw_user10'),
('user11@example.com', 'hashed_pw_user11'),
('user12@example.com', 'hashed_pw_user12'),
('user13@example.com', 'hashed_pw_user13'),
('user14@example.com', 'hashed_pw_user14'),
('user15@example.com', 'hashed_pw_user15'),
('user16@example.com', 'hashed_pw_user16'),
('user17@example.com', 'hashed_pw_user17'),
('user18@example.com', 'hashed_pw_user18'),
('user19@example.com', 'hashed_pw_user19'),
('user20@example.com', 'hashed_pw_user20'),
('user21@example.com', 'hashed_pw_user21'),
('user22@example.com', 'hashed_pw_user22'),
('user23@example.com', 'hashed_pw_user23'),
('user24@example.com', 'hashed_pw_user24'),
('user25@example.com', 'hashed_pw_user25'),
('user26@example.com', 'hashed_pw_user26'),
('user27@example.com', 'hashed_pw_user27'),
('user28@example.com', 'hashed_pw_user28'),
('user29@example.com', 'hashed_pw_user29'),
('user30@example.com', 'hashed_pw_user30');


INSERT INTO profiles (user_id, username, first_name, last_name, bio)
VALUES
(1,  'user1',  'Ali',      'Valiyev',    'Demo bio for user1'),
(2,  'user2',  'Bek',      'Karimov',    'Demo bio for user2'),
(3,  'user3',  'Jasur',    'Tursunov',   'Demo bio for user3'),
(4,  'user4',  'Dilshod',  'Abdullayev', 'Demo bio for user4'),
(5,  'user5',  'Aziz',     'Rustamov',   'Demo bio for user5'),
(6,  'user6',  'Sardor',   'Islomov',    'Demo bio for user6'),
(7,  'user7',  'Anvar',    'Jo‘rayev',   'Demo bio for user7'),
(8,  'user8',  'Otabek',   'Shukurov',   'Demo bio for user8'),
(9,  'user9',  'Rustam',   'To‘xtayev',  'Demo bio for user9'),
(10, 'user10', 'Farrux',   'Aliyev',     'Demo bio for user10'),
(11, 'user11', 'Doston',   'Ergashev',   'Demo bio for user11'),
(12, 'user12', 'Jamshid',  'Sobirov',    'Demo bio for user12'),
(13, 'user13', 'Shohruh',  'Qodirov',    'Demo bio for user13'),
(14, 'user14', 'Sherzod',  'Mamatov',    'Demo bio for user14'),
(15, 'user15', 'Sanjar',   'Yusupov',    'Demo bio for user15'),
(16, 'user16', 'Javohir',  'Rahmonov',   'Demo bio for user16'),
(17, 'user17', 'Komil',    'Hamidov',    'Demo bio for user17'),
(18, 'user18', 'Bahrom',   'Qo‘chqorov', 'Demo bio for user18'),
(19, 'user19', 'Erkin',    'Norqobilov', 'Demo bio for user19'),
(20, 'user20', 'Shaxboz',  'Soliyev',    'Demo bio for user20'),
(21, 'user21', 'Muhammad', 'Eshonov',    'Demo bio for user21'),
(22, 'user22', 'Zuhra',    'Abdullayeva', 'Demo bio for user22'),
(23, 'user23', 'Nilufar',  'Sultonova',  'Demo bio for user23');
